services:
  juno-satellite:
    image: junobuild/satellite:latest
    ports:
      - 5987:5987
      - 5999:5999
    volumes:
      - juno_satellite:/juno/.juno
      # TypeScript config (commented out)
      - ./juno.dev.config.ts:/juno/juno.dev.config.ts
      # JSON config (active)
      # - ./juno.dev.config.json:/juno/juno.dev.config.json
      - ./target/deploy:/juno/target/deploy/

volumes:
  juno_satellite:
