// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

import type { Principal } from '@dfinity/principal';
import type { ActorMethod } from '@dfinity/agent';
import type { IDL } from '@dfinity/candid';

export interface ReputationData {
  'last_calculation' : bigint,
  'user_key' : string,
  'reputation_basis' : number,
  'tag_key' : string,
  'reputation_rewards' : number,
  'vote_weight' : number,
  'has_voting_power' : boolean,
  'reputation_total_effective' : number,
}
export type Result = { 'Ok' : string } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : number } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : ReputationData } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : boolean } |
  { 'Err' : string };
export interface _SERVICE {
  'build_version' : ActorMethod<[], string>,
  'create_document_key_for_reputation' : ActorMethod<[string, string], Result>,
  'create_document_key_for_tag' : ActorMethod<[string, string], Result>,
  'create_document_key_for_user' : ActorMethod<[string], Result>,
  'create_document_key_for_vote' : ActorMethod<
    [string, string, string],
    Result
  >,
  'get_user_reputation' : ActorMethod<[string, string], Result_1>,
  'get_user_reputation_full' : ActorMethod<[string, string], Result_2>,
  'recalculate_reputation' : ActorMethod<[string, string], Result_1>,
  'validate_document_key' : ActorMethod<[string, string], Result_3>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];