// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

import type {_SERVICE as SatelliteActor, Result} from './satellite.did';
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';

export const buildVersion = async (): Promise<string> => {
	const {build_version} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await build_version();
}

export const getUserReputation = async (value0: string, value1: string): Promise<Result> => {
	const {get_user_reputation} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_user_reputation(value0, value1);
}

export const recalculateReputation = async (value0: string, value1: string): Promise<Result> => {
	const {recalculate_reputation} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await recalculate_reputation(value0, value1);
}