// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

import type {_SERVICE as SatelliteActor, GraphData, GraphEdge, GraphNode, ReputationData, Result, Result_1, Result_2, Result_3, Result_4} from './satellite.did';
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';

export const buildVersion = async (): Promise<string> => {
	const {build_version} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await build_version();
}

export const checkUsernameAvailabilityScan = async (value0: string): Promise<Result> => {
	const {check_username_availability_scan} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await check_username_availability_scan(value0);
}

export const createDocumentKeyForReputation = async (value0: string, value1: string): Promise<Result_1> => {
	const {create_document_key_for_reputation} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await create_document_key_for_reputation(value0, value1);
}

export const createDocumentKeyForTag = async (value0: string, value1: string): Promise<Result_1> => {
	const {create_document_key_for_tag} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await create_document_key_for_tag(value0, value1);
}

export const createDocumentKeyForUser = async (value0: string, value1: string): Promise<Result_1> => {
	const {create_document_key_for_user} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await create_document_key_for_user(value0, value1);
}

export const createDocumentKeyForVote = async (value0: string, value1: string, value2: string): Promise<Result_1> => {
	const {create_document_key_for_vote} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await create_document_key_for_vote(value0, value1, value2);
}

export const getGraphData = async (value0: string, value1: string): Promise<Result_2> => {
	const {get_graph_data} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_graph_data(value0, value1);
}

export const getUserReputation = async (value0: string, value1: string): Promise<Result_3> => {
	const {get_user_reputation} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_user_reputation(value0, value1);
}

export const getUserReputationFull = async (value0: string, value1: string): Promise<Result_4> => {
	const {get_user_reputation_full} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_user_reputation_full(value0, value1);
}

export const recalculateReputation = async (value0: string, value1: string): Promise<Result_3> => {
	const {recalculate_reputation} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await recalculate_reputation(value0, value1);
}

export const validateDocumentKey = async (value0: string, value1: string): Promise<Result> => {
	const {validate_document_key} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await validate_document_key(value0, value1);
}