name: Deploy to Juno

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Install Juno CLI
        run: npm install -g @junobuild/cli

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Build Backend
        run: |
          cd src/satellite
          cargo build --target wasm32-unknown-unknown
          cd ../..
          juno dev build --headless

      - name: Verify WASM File
        run: |
          if [ ! -f "./target/deploy/satellite.wasm.gz" ]; then
            echo "WASM file not found at ./target/deploy/satellite.wasm.gz"
            exit 1
          fi

      - name: Deploy Backend
        uses: junobuild/juno-action@main
        with:
          args: upgrade -t s -s ./target/deploy/satellite.wasm.gz --headless
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}

      - name: Build Frontend
        run: npm run build

      - name: Deploy Frontend
        uses: junobuild/juno-action@main
        with:
          args: deploy --headless
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}